# Generated by Django 2.2 on 2020-01-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Store', max_length=200)),
                ('category', models.CharField(choices=[('Regular', 'Regular'), ('Exclusive', 'Exclusive'), ('Premium', 'Premium')], default='Regular', max_length=200)),
                ('mealDescription', models.TextField(default=' Saturday : Rice + Egg + Veg Sunday :  Rice + Fish + VegMonday :  Rice + Chicken + VegTuesday : Rice + Mutton + Veg Wednesday :  Rice + Fish + VegThursday : Rice + Chicken + Veg Friday :  Biriyani', max_length=2000)),
                ('price', models.FloatField(default=39.99, max_length=200)),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
            ],
        ),
    ]
