# Generated by Django 2.2 on 2020-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='foodphoto',
            field=models.ImageField(blank=True, default='default.png', upload_to='plans'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='mealDescription',
            field=models.TextField(default=' Saturday : Rice + Egg + Veg \nSunday :  Rice + Fish + Veg \nMonday :  Rice + Chicken + Veg \nTuesday : Rice + Mutton + Veg \nWednesday :  Rice + Fish + Veg \nThursday : Rice + Chicken + Veg \nFriday :  Biriyani\n', max_length=2000),
        ),
    ]
