# Generated by Django 2.2 on 2020-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200127_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='mealDescription',
            field=models.TextField(default='Saturday : Rice + Egg + Veg \nSunday :  Rice + Fish + Veg \nMonday :  Rice + Chicken + Veg \nTuesday : Rice + Mutton + Veg \nWednesday :  Rice + Fish + Veg \nThursday : Rice + Chicken + Veg \nFriday :  Biriyani\n', max_length=2000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Plan Name', max_length=200),
        ),
    ]
