# Generated by Django 2.2 on 2020-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20200128_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='foodphoto',
            field=models.ImageField(blank=True, default='default.gif', upload_to='plans'),
        ),
    ]
