# Generated by Django 2.2 on 2020-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20200128_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='mealDescription',
            field=models.TextField(default='Saturday : Rice + Egg + Veg \nSunday :  Rice + Fish + Veg \n\nMonday :  Rice + Chicken + Veg \n\nTuesday : Rice + Mutton + Veg \n\nWednesday :  Rice + Fish + Veg \n\nThursday : Rice + Chicken + Veg \n\nFriday :  Biriyani\n\n', max_length=2000),
        ),
    ]
