# Generated by Django 2.2 on 2020-01-29 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dguys', '0003_auto_20200130_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dguy',
            name='boy',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
