# Generated by Django 2.2 on 2020-01-31 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0005_auto_20200128_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='01719000000', max_length=100)),
                ('address', models.CharField(default='8/8 Nakahlpra', max_length=100)),
                ('cost', models.FileField(default=0.0, upload_to='')),
                ('duration', models.IntegerField(choices=[(7, 7), (14, 14), (28, 28)], default=7, max_length=200)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enroller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
        ),
    ]
