# Generated by Django 2.2 on 2020-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='cost',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
