# Generated by Django 2.2 on 2020-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='Share your experience with this meal plan , it matters! ❤ ', max_length=10000),
        ),
    ]
