# Generated by Django 2.2 on 2020-02-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20200131_1550'),
        ('enrolments', '0004_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='enrolment',
        ),
        migrations.AddField(
            model_name='rating',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
        ),
    ]
