# Generated by Django 2.2 on 2020-01-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Store', max_length=200)),
                ('description', models.TextField(default='Please something about your shop', max_length=200)),
                ('location', models.CharField(choices=[('Farmgate', 'Farmgate'), ('Dhanmondi', 'Dhanmondi'), ('Wari', 'Wari')], default='Farmgate', max_length=200)),
                ('category', models.CharField(choices=[('HomeMade', 'HomeMade'), ('Professional', 'Professional')], default='HomeMade', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, default='default.png', upload_to='pics')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
