# Generated by Django 2.2 on 2020-01-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='thumbnail',
            field=models.ImageField(blank=True, default='store.gif', upload_to='pics'),
        ),
    ]
