# Generated by Django 2.2 on 2020-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200209_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='thumbnail',
            field=models.ImageField(blank=True, default='store.gif', null=True, upload_to='pics'),
        ),
    ]
