# Generated by Django 2.2 on 2020-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200303_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='thumbnail',
            field=models.ImageField(default='store.gif', upload_to='pics'),
        ),
    ]
